### ISSUE TITLE
本地安装ok ,服务器上安装走到 miss() 中去了。

### ISSUE THREAD

**Issue by 13823761206** [72crm/72crm#16]
index.php/admin/install/index.html
`    // miss 路由：处理没有匹配到的路由规则
    public function miss()
    {

        if (Request::instance()->isOptions()) {
            return ;
        } else {
            echo '悟空软件';
        }
    }`

**Comment by zoulux** [comment]
请问是什么原因

**Comment by gengxiaoxu** [comment]
服务器设置首页运行 index.html 优先




------------------ 原始邮件 ------------------
发件人: "jake"<notifications@github.com>;
发送时间: 2019年9月7日(星期六) 下午2:06
收件人: "72crm/72crm"<72crm@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [72crm/72crm] 本地安装ok ,服务器上安装走到 miss() 中去了。 (#16)




请问是什么原因
